name: salon_manager
description: Salon manager app (Flutter)
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State & routing & i18n
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  easy_localization: ^3.0.5
  intl: ^0.20.2

  # UI (اختیاری)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/en.json
    - assets/i18n/fa.json

  # اگر پوشه فونت‌ها را نداری، فعلاً این بخش را حذف کن
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn/Vazirmatn-Bold.ttf
          weight: 700
