name: Android Debug APK

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "platforms;android-35" "build-tools;35.0.0"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK (dev flavor)
        run: flutter build apk --debug --dart-define=FLAVOR=dev

      # 🔎 گام دیباگ: لیست کردن مسیرهای خروجی برای اینکه ببینیم APK دقیقاً کجا ساخته شده
      - name: Show produced outputs
        run: |
          echo "== ls outputs =="
          ls -R build/app/outputs || true
          echo "== find *.apk =="
          find build -type f -name "*.apk" -print || true

      # ⬆️ آپلود مقاوم: چند الگو برای همه‌ی حالت‌های ممکن
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/apk/**/*.apk
            build/**/outputs/**/*.apk
          if-no-files-found: warn
          retention-days: 7