name: Android Debug APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: flutter doctor
        run: flutter doctor -v

      - name: Build debug APK (dev flavor)
        run: |
          set -e
          flutter pub get
          flutter build apk --debug -v --dart-define=FLAVOR=dev

      # هر APK زیر build/ را جمع می‌کنیم
      - name: Collect APKs
        run: |
          set -e
          mkdir -p artifacts
          found=false
          # همه‌ی .apk‌ها را پیدا و در artifacts کپی کن
          while IFS= read -r -d '' f; do
            found=true
            echo "Copying $f"
            cp -v "$f" "artifacts/$(basename "$f")"
          done < <(find build -type f -name "*.apk" -print0)
          if [ "$found" = false ]; then
            echo "❌ No APKs found under build/"
            echo "== quick tree =="
            find build -maxdepth 4 -type d -print || true
            exit 2
          fi
          echo "✅ Collected APKs:"; ls -l artifacts

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apks
          path: artifacts/*.apk
          if-no-files-found: error
          retention-days: 7

      - name: Show outputs tree (debug)
        if: always()
        run: |
          echo "== dirs =="
          find build -maxdepth 4 -type d -print || true
          echo "== apks =="
          find build -type f -name "*.apk" -print || true