name: Android Debug APK
on:
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    env:
      PUB_HOSTED_URL: https://pub.dev
      FLUTTER_STORAGE_BASE_URL: https://storage.googleapis.com
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" || true
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.35.2'

      - name: flutter --version
        run: flutter --version

      - name: Flutter pub get
        run: flutter pub get

      # اگر build_runner لازم نیست، حذفش نگه داشتیم که اجرا نشه
      # - name: Generate code (build_runner)
      #   run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Debug APK (verbose)
        run: flutter build apk --debug -v --dart-define=FLAVOR=dev

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
